### ISSUE TITLE
Rename default branch to `master`

### ISSUE THREAD

**Issue by qhua948** [openshift/managed-scripts#2]
Following our old conventions, we should consider reverting the default branch to `master`

**Comment by georgettica** [comment]
I am all for making the branch `main`

I understand that there are old conventions, but this is the way the world works now and if we have the option, I would suggest migrating to the new standard

Also I guess we should have that conversation of working with `main` on other repos

**Comment by qhua948** [comment]
+1, I think for fresh repos we should tick to `main`
