### ISSUE TITLE
Add yq to command line tools

### ISSUE THREAD

**Issue by k-wall** [openshift/managed-scripts#37]
In our use-case (Managed Kafka) we are using `oc adm inspect` to grab kubernetes state.  In some cases, we want to exclude some fields from the yaml output files generated by `inspect`.    Unfortunately the `oc adm inspect` command line does not support a `--output=json` mode, so we cannot use `jq`.

Could you consider adding `yq` to the command line tools available to an ocm backplace script?

Happy to raise a PR.

**Comment by georgettica** [comment]
I'll let the maintailers of this repo to respond (also i'll mention it in the place they respond more ofter)

**Comment by wanghaoran1988** [comment]
@k-wall This make sense to me, could you go ahead create a PR to add that in our base image?

**Comment by georgettica** [comment]
We could add a different tool that should be able to do both (bit is less common)
https://github.com/itchyny/gojq

It seems to:
- have yaml support
- have golang types and functions
- purely written in go (so contributions are easier)

**Comment by k-wall** [comment]
> We could add a different tool that should be able to do both (bit is less common) https://github.com/itchyny/gojq

I don't see an RPM for gojq.  There is a bugzilla for it, https://bugzilla.redhat.com/show_bug.cgi?id=2009498 but that is being reviewed.

The Dockerfile could build it from source, but wouldn't that create a supply chain concern?

**Comment by georgettica** [comment]
I guess that now that we have the bz, we can create the yq and migrate away once we have it

**Comment by k-wall** [comment]
https://listman.redhat.com/archives/ubi/2021-November/msg00005.html

**Comment by k-wall** [comment]
I hit a wall trying to get the package into UBI
