### ISSUE TITLE
Injection attack possibility in kafka.py.

### ISSUE THREAD

**Issue by k-wall** [openshift/managed-scripts#84]
Currently this library doesn't guard against the injection attacks.  For instance, a malicious user could pass in a specially crafted kafka instance name or topic name (containing a white space) to cause undesired execution effects.  Best practice tells us we should always code to avoid this possibility.

Building the cmd arrays explicitly, rather than splitting on whitespace, would be one possible resolution.

https://github.com/openshift/managed-scripts/blob/3211e575e9d718cb58c11d701fceb3dee26f5fe3/scripts/CSSRE/lib/py/kafka.py#L91

@robshelly

**Comment by feichashao** [comment]
Thank you for raising the issue! Given the PR is merged, are we good to close this issue?

**Comment by robshelly** [comment]
Yes this can be closed now. Thanks for pointing out the issue @k-wall.
